### ISSUE TITLE
Input variables not updated

### ISSUE THREAD

**Issue by richardpayne** [overturetool/overture-fmu#1]
The FMU exported by Overture does not appear to receive input correctly from the COE.
I have created a few versions of the three tank model and have put them in Dropbox here: https://www.dropbox.com/sh/hjhnbhaxzyo3pth/AACyeLTrt8-K7fkJ2X6g0opva?dl=0

Version 1: original VDM-RT model with manual FMU export
Version 2: new version of VDM-RT model with auto export
Version 3: new version of VDM-RT model + test variables (output = input) with auto export
Version 4: new version of VDM-RT model + test variables (output = 1.0, 0.0 periodically to test output of FMU) with auto export

Version 2 is the one I really want to work. I created versions 3 and 4 to work out what was happening.

**Comment by richardpayne** [comment]
I believe this may be due to the use of static variables - using the pattern defined on the INTO-CPS site, I defined input values as static - may this be the problem?

**Comment by lausdahl** [comment]
This is fixed in the new version where is uses a `HardwareInterface` class instead.

213578c2c9307268b24d54737d8bc9f009b764dc
