### ISSUE TITLE
"conflicting handlers" for FMU exporter

### ISSUE THREAD

**Issue by cfjkoenig** [overturetool/overture-fmu#2]
After having installed the FMU plugin for Overture (2.3.0) via the way described on the INTO-CPS release site, I get the following error message:

> eclipse.buildId=unknown
> java.version=1.8.0_66
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
> Command-line arguments:  -os win32 -ws win32 -arch x86_64
> 
> org.eclipse.ui
> Error
> Tue Feb 23 10:15:02 CET 2016
> Conflicting handlers for org.overture.fmi.ide.fmuexport.export: 
> {org.overture.fmi.ide.fmuexport.commands.ExportFmuHandler} vs {org.overture.fmi.ide.fmuexport.commands.ExportFmuHandler}

In addition, in all the vdm-rt classes, I get an error message in line 1, saying "Class World duplicates World". 
However, an FMU is generated. I don't know yet if that FMU is working, though.

**Comment by lausdahl** [comment]
fixed in f1638f3baff74f4b76c5d8842b3c3a134e0efb50
