### ISSUE TITLE
Simulation hanging with Overture FMUs

### ISSUE THREAD

**Issue by kgpierce** [overturetool/overture-fmu#27]
The following multi-model, when using updated VDM FMUs, hangs at the end of simulation with no obvious error message: https://github.com/into-cps/case-study_uav_swarm/tree/development

The "3-UAV-DE_only" multi-model only runs the DE part of the model (one global controller and three replicated UAV controllers), showing some issue with the Overture side.

**Comment by lausdahl** [comment]
How do you detect that it hangs?

If I simulate the model using mm "3-UAV-DE_only":

- algorithm = `variable step`
- Initial step size = `1e-9`
- Minimum step size = `5e-9`
- Maximum step size = `10.1`

the tail of the COE output is:

```
DoStep VDM time: 1.0E10
DoStep VDM time: 1.0E10 - completed
DEBUG [Thread-1] (StateCache.java:149) - Sync output to fmi struct name: 'System.hwi.throttleOut.value' value: '30.53999999999997' valueref: '13'
DEBUG [Thread-1] (StateCache.java:149) - Sync output to fmi struct name: 'System.hwi.yawOut.value' value: '0.0' valueref: '14'
DEBUG [Thread-1] (StateCache.java:149) - Sync output to fmi struct name: 'System.hwi.pitchOut.value' value: '-0.35' valueref: '6'
DEBUG [Thread-1] (StateCache.java:149) - Sync output to fmi struct name: 'System.hwi.rollOut.value' value: '0.35' valueref: '10'
DoStep waiting for next DoStep at: 10.000002
terminate
terminate
terminate
terminate
```

showing 4 terminate calls one global controller and 3 normal controllers.

**Comment by kgpierce** [comment]
It turns out this is a problem with 20-sim and multiple instance FMUs.
