### ISSUE TITLE
All c sources must be listed in `CoSimulation/SourceFiles`

### ISSUE THREAD

**Issue by lausdahl** [overturetool/overture-fmu#31]
All c source files must be listed under `CoSimulation/SourceFiles` using the `name` attribute relative to the source directory. Dymola just lists one static entry "all.c" which includes other files.

**Comment by bandurvp** [comment]
This is required presently for use with the INTO-CPS app, it will prevent loading of a standalone FMU if this list is missing.

**Comment by bandurvp** [comment]
Hi Kenneth, I've made the required connection to the field you exposed in the model description class and pushed the change to the branch vpb/fmu-list-sources.  I've changed this to a "bug" because of the problem mentioned in my previous comment.

**Comment by lausdahl** [comment]
Can it be merged into development? If you did any changed to VDM2C then these should be made available first either through SNAPSHOT or release in artifactory for vdm2c

**Comment by bandurvp** [comment]
I had to make no changes to vdm2c for this feature.  So I suppose it can be merged.

Victor

**Comment by lausdahl** [comment]
You must have a local change in VDM2C it cannot build if I merge it.

**Comment by bandurvp** [comment]
Of course I do, my apologies... I've just pushed it to development.

Victor
