### ISSUE TITLE
Incorrect access to static fields generated in FmuModel.cpp

### ISSUE THREAD

**Issue by bandurvp** [overturetool/overture-fmu#37]
Port variables in the HardwareInterface class are `public static`, but they are accessed with the `GET_FIELD` macro in FmuModel.cpp, so the exported source code FMU does not compile.

**Comment by lausdahl** [comment]
I do not unserstand this issue. The import feature imports the scalar variables as public port instance variables. It is correct that the `HardwareInterface` is static in the system class but not the instance variables inside it.

**Comment by bandurvp** [comment]
It's just that the fields inside HardwareInterface are public but also static.  So they get generated as globals.  But they are accessed using GET_FIELD, which does not work for globals.

For example, the line follower has the following in HardwareInterface:

      public static leftVal : RealPort := new RealPort(0.0);

But in FmuModel.cpp, in the function syncInputsToModel(), the corresponding variable is accessed like this:

    TVP p = GET_FIELD(HardwareInterface,HardwareInterface,g_System_hwi,rightVal);

and gET_FIELD then looks for the field m_HardwareInterface_rightVal in the structure corresponding to HardwareInterface.  But because it is a public static in HardwareInterface, m_HardwareInterface_rightVal is not a field of the generated struct.  The correct global is g_HardwareInterface_rightVal.

Victor

**Comment by lausdahl** [comment]
I get the static part but that does not look like this is reflected in the code. See the import: https://github.com/overturetool/overture-fmu/blob/development/core/fmu-import-export/src/main/java/org/overturetool/fmi/imports/ImportModelDescriptionProcesser.java#L341-L343

none of these have static

for the C code export a type check phase could be added that checks that the ports are none static since you need different code for the two cases, but it look like the standard is none static if the importer is used

**Comment by bandurvp** [comment]
This is exactly what I was wondering about.  modelDescription import does not result in statics, so this is good.  I don't think we should do anything about it in that case, since modelDescription import is the official workflow.  The HardwareDescription file must have been written by hand for the line follower.  I'll close the issue.

Victor

**Comment by lausdahl** [comment]
Sounds likely, but if you do not check this you may export invalid code without warning the user. The check should be easy to add since the model description  generator already have the definitions.

**Comment by bandurvp** [comment]
What would you rather have, invalid code with a warning to the user, or just stop export if statics are detected?

Victor

**Comment by lausdahl** [comment]
I think the easiest is to just disallow it (error) then it is a small fix. Technically this is only needed for the c code export.

**Comment by bandurvp** [comment]
I agree, I'll do that.

Victor

**Comment by bandurvp** [comment]
OK I have a mechanism for detecting whether the HWInterface class has statics, but I can not figure out how where to use it.  I can't figure out where the SC exporter gets invoked.

Victor

**Comment by bandurvp** [comment]
The check is complete, it is on branch vpb/hwinterface-statics, commit 7bcf71a0abd4c20b0912514fae981fb2996e7604.
