### ISSUE TITLE
Error when more than 20 ScalarVariables

### ISSUE THREAD

**Issue by richardpayne** [overturetool/overture-fmu#4]
I get an ArrayIndexOutOfBoundsException when co-simulating with VDM FMUs with a ScalarVariable number greater than 19:

TRACE [Thread-2] (Util.java:176) - getRaw real, comp: {guid_5_sensor_sdp}.controller indices: [17, 18, 19, 21]
Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: 21
        at org.crescendo.fmi.CrescendoFmu.GetReal(CrescendoFmu.java:256)
        at org.intocps.java.fmi.service.ProtocolDriver.run(ProtocolDriver.java:85)
        at java.lang.Thread.run(Unknown Source)

**Comment by lausdahl** [comment]
Thats by design: https://github.com/overturetool/overture-fmu/blob/development/core/fmi-interpreter/src/main/java/org/crescendo/fmi/StateCache.java#L38

but this is clearly not good enough for a larger model. Any suggestion to what size I should designe as max? 500

**Comment by richardpayne** [comment]
Hi Kenneth,

Is there a way to parse the ModelDescription file to determine the number of variables first?

Otherwise, I’d suggest setting this value for the largest possible.

Cheers,
Richard
