### ISSUE TITLE
The VDM library is not compatible with Visual C

### ISSUE THREAD

**Issue by lausdahl** [overturetool/overture-fmu#66]
```c

...(int size,..){
TVP elements[size];

}
```
is not valid since the size needs to be a constant

**Comment by bandurvp** [comment]
@lausdahl , is the variable size array you mentioned the only feature that doesn't work with VC?  This is an interesting issue having to do with standards conformance in GCC and it's not so easy to handle in general.  Please let me know.

**Comment by lausdahl** [comment]
its the only one mentioned by the compiler :-) but there are so many that it may be giving up before it potentially reports others.

**Comment by bandurvp** [comment]
The strange thing is that if I turn all the warnings on it complains that variadic macros are also not C89, yet CLPs C89 compilers work on the code as it is...  I'll convert the arrays to use ```malloc``` and we can try that, does that work for you?

**Comment by lausdahl** [comment]
I dont really care I just observed this. But I do not see any other easy way to fix it

**Comment by bandurvp** [comment]
I'll do this then and push the change.

**Comment by bandurvp** [comment]
I've pushed the change to vpb/development in VDM2C, this should be enough to test, otherwise we'd have to release the FMU exporter to use a new version of VDM2C.
