### ISSUE TITLE
Strange loop index in for all

### ISSUE THREAD

**Issue by lausdahl** [overturetool/overture-fmu#75]
Look at the generated code for this:

```
for all idx in set dom {1|->2} do
(
skip;
);
```

```c
/* Controller.vdmrt 38:20 */
TVP forLoop_1 = vdmMapDomGC(newMapVarToGrowGC(1, 5, NULL, newIntGC(1, NULL), newIntGC(2, NULL)), NULL);

int forLoop_2 = vdmCloneGC(0, NULL);

ASSERT_CHECK_COLLECTION(forLoop_1);

UNWRAP_COLLECTION(forLoop_3, forLoop_1);

while (forLoop_2 < forLoop_3-> size) {
  {

    TVP idx = forLoop_3->value[forLoop_2];
    /* Controller.vdmrt 40:1 */
    {
      /*  Skip  */
    };

    forLoop_2 = forLoop_2 + 1;
  };
};
```

this generates this warning: 

```
Controller.c:122:5: warning: incompatible pointer to
      integer conversion initializing 'int' with an expression of type 'struct TypedValue *' [-Wint-conversion]
int forLoop_2 = vdmCloneGC(0, NULL)
    ^           ~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

which is fair it seems very stange to create a loop index using anything but a plain number, its in normal scope so should not be collected anyway.

It looks like `forLoop_2` should just start at `0`

**Comment by bandurvp** [comment]
The problematic line `int forLoop_2 = vdmCloneGC(0, NULL)` I think comes from the GC transformation, so I'll assign @peterwvj to look at it.  It should be a simple assignment `int forloop_2 = 0;`.  The fact that it works is a fluke, since `vdmCloneGC(NULL, NULL)`, which is what `vdmCloneGC(0, NULL)` actually is, returns `NULL` in turn, so `forLoop_2` is actually initialized to 0!

**Comment by lausdahl** [comment]
yes and thats the correct value for this case. NULL is 0 so it works but let see if he can fix it then we also avoid the warnings.

**Comment by peterwvj** [comment]
Any reason for submitting this issue in overturetool/overture-fmu ? It looks like this is solely a VDM2C issue. Can I move the issue over to VDM2C?

**Comment by lausdahl** [comment]
You can move it. Its reported here since it is found using this tool.

**Comment by peterwvj** [comment]
Fixed https://github.com/overturetool/vdm2c/issues/119
