### ISSUE TITLE
Could we include the vdm model in C code fmus for better debugging

### ISSUE THREAD

**Issue by lausdahl** [overturetool/overture-fmu#76]
I'm trying to debug a C code FMU but I have trouble finding the VDM code that resembles the C code. There is references in the C code but I do not know which VDM model it is generated from.

Suggestion is to include the VDM model as in the tool wrapper. Additionally we could add some checksum elements of the model files similar to how the `link`s are done in the tool wrapper.

**Comment by bandurvp** [comment]
Hi @lausdahl , this is currently the case.  The model is in `resources`.
