### ISSUE TITLE
There is a clash between `MATH.h` and the windows math library

### ISSUE THREAD

**Issue by lausdahl** [overturetool/overture-fmu#77]
The `Math` library in VDM clashes with the math library on Windows so I suggest to change math to `VdmMath`.

**Comment by bandurvp** [comment]
I don't believe that this is a C generator issue.  First, the fixed runtime math support library consists of two files, `MATHLib.c` and `MATHLib.h`.  Second, if the clas is with the name of the VDM Math library file `MATH.vdmrt` then perhaps that file's name is the one that should be changed.  I don't think it makes sense to deal with this at the generator level.

**Comment by lausdahl** [comment]
I think it is the MATH.vdmrt “math” that classes with the one on windows. This is a VDM library so we cannot change its name so I suggest that the c generator does something with output class names to avoid clasing with known system libraries. It makes no sense to change the library name because it works fine in VDM I also think that the math library was made to essentially match the common system libraries.

**Comment by bandurvp** [comment]
I'm going to move this issue to VDM2C because the renaming should take place there, where it needs to be a renaming refactoring.
