### ISSUE TITLE
CLI invocation

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture-fmu#8]
Hiya,

Is there anyway to invoke the FMI export via the command-line or a maven plugin? I snooped around the code and it didn't look like it.

**Comment by lausdahl** [comment]
No at the moment this is only available as from within the Overture IDE

**Comment by ldcouto** [comment]
Yeah, I know :)

It's no problem for now (or ever, really). I'd really like to have some Continuous Co-Sim deployed for Y3. It would make our case study nicer. Do you think we can put this on the roadmap for Y3?

**Comment by lausdahl** [comment]
yes, the code isn’t really IDE dependent so it can just be moved to a jar with some basic dependencies to the core of overture

**Comment by lausdahl** [comment]
implemented in b4b6eb2abb1e20c35f4accad5581d37453dc25c3
